"""Added date column

Revision ID: e23cb2488d3d
Revises: 
Create Date: 2026-02-19 16:53:59.458314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23cb2488d3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reps', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.String(), nullable=False))
        batch_op.drop_column('rep')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rep', sa.INTEGER(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('reps')

    # ### end Alembic commands ###
